### ISSUE TITLE
Update to MPAS-Analysis v0.7.0

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/a-prime#29] opened 2018-01-26 18:27 UTC
I just released [MPAS-Analysis v0.7.0](https://github.com/MPAS-Dev/MPAS-Analysis/releases/tag/v0.7.0), so it would be great to have A-Prime support the new features included in this release.

There are some issues to discuss and some changes that will be needed.

Issues to discuss:
* Will A-Prime support new Antarctic plots?  If so, we need to make sure the appropriate mapping files are available on all supported machines (so they are not generated each time).  The SOSE observations also need to be available everywhere.
* Will A-Prime use MPAS-Analysis' HTML generation?
* Will A-Prime support runs with ice-shelf cavities (plots of melt rates)?  If so, the melt observations need to be available everywhere.
* Will A-Prime support plotting against a reference run?

Changes:
* We need to be using e3sm-unified v1.1.2 on all supported machines (therefore we need to test that a-prime works with this version)
* A few config options have changed in MPAS-Analysis, notably:
  * [runs]/referenceRunConfigFile has been added (if you want to use a reference run)
  * [streamfunctionMOC]/regionMaskFiles has been replaced with [regions]/regionMaskDirectory

**Comment by kevans32** [comment] 2018-01-26 18:32
Very cool. Would you need any help with testing/evaluation of this update? I think a phone call might be useful. We did want to support comparison's to a reference run but Dave was clear that we were not to do much development on A-PRIME, especially if its new plots that are specific for only certain runs/simulations. That said, I am sure if many folks want the feature he would be amenable.

**Comment by xylar** [comment] 2018-01-26 18:51
I see.  I agree, let's discuss.  MPAS-Analysis certainly isn't going to cease development anytime soon so it will be important to know how our enhancements make their way into future E3SM runs if not through A-Prime.

**Comment by milenaveneziani** [comment] 2018-01-26 18:51
I think what we definitely want is to point to the MPAS-Analysis html page and update things about the conda environment and the MOC region mask file.
A-prime was designed to address the coupled model priority metrics: if people want to look more closely at the ocean and ice, they could just run MPAS-Analysis standalone.
The comparison to a ref run is an open question: I am happy to address it in the next PR if people want it. @golaz: do you have an opinion on this?
It will basically entail the running of a-prime (ocean only part) for the reference run *first*, and then a re-running to compare the test run with the reference run.

**Comment by milenaveneziani** [comment] 2018-01-26 18:55
For the future, (and I have said this many times, sorry for repeating myself), these are the things we definitely want to update a-prime with: script to plot the online MOC and ocean-basin computations of OHC and SST,T, and S trends.

**Comment by golaz** [comment] 2018-01-26 19:02
I would encourage you to have a discussion on how you envision that users will be calling A-Prime and MPAS-Analysis in the future. Should MPAS-Analysis be called as stand-alone package? Or should A-Prime be modified to (optionally?) call the full MPAS-Analysis, including the html interface?

I don't have a strong opinion either way. My hope is that ultimately all these packages would be incorporated and callable within the E3SM automated processflow.

**Comment by kevans32** [comment] 2018-01-26 20:36
agreed. @golaz could we have some time in the next coupled group call agenda to discuss? Or is it too jam packed with v1 activities that we should have a separate call just on this?

**Comment by golaz** [comment] 2018-01-26 21:55
I'm not planning to have a water cycle coupled telecon this Monday. I'm only having them on a as-needed basis. We could have one specifically to discuss this, but it might be more productive to have the discussion within a smaller group involving key A-Prime and MPAS-Analysis developers. I don't have to be involved, but I can if you'd like.

**Comment by xylar** [comment] 2018-01-26 22:10
It sounds like it might make sense to use one of LANL's special topic meeting slots to have this discussion.  Those are at 10 am MST on Monday and Thursday.  This coming week is bad for me because of the ALCC deadline on Thursday but the week after could work.

**Comment by kevans32** [comment] 2018-01-29 04:01
Next Monday the 5th works for me, but it needs to work for @salilmahajan as well.

**Comment by milenaveneziani** [comment] 2018-01-29 05:59
If both a-prime and mpas-analysis are packages/softwares that are callable from the acme-process workflow package, then I personally think it doesn't make sense to have a-prime call mpas-analysis in full. A-prime was envisioned as a first analysis software to evaluate coupled models at first glance, with in-depth analysis left to component-specific analysis. It was also conceived as something that should not evolve much in time (except for making sure updated conda environments do not break the analysis, I guess). On the contrary, MPAS-Analysis is something that will continually evolve in time, as @xylar said, and will eventually be a package with the possibility to evaluate MPAS ocean and ice fields in a fairly complete way. Again, if both softwares can be called by the users through the acme-processing system, it seems OK to keep them separate.
My 2 c.

**Comment by salilmahajan** [comment] 2018-01-29 14:32
?Yes, Monday 5th works for me too! I am available all day.


Thanks,

Salil.

________________________________

**Comment by kevans32** [comment] 2018-01-30 13:55
All right 10MST it is, Mon Feb 5. Xylar is there a # you guys call into? Is it this part of a larger LANL group discussion at that time?

**Comment by milenaveneziani** [comment] 2018-01-30 17:16
Apparently Feb 5 is already taken.
We can also schedule a gotomeeting session without sitting in the same room. I have checked the gotomeeting calendar and it looks like gotomeeting2 is available on Th from 11am to 2pm (MST): would 11 or 12 or 1pm work for you this coming Th (Feb 1)? Next Th the 8th is too close to Ocean Sciences and I know I'll be in the midst of finishing up my poster..

**Comment by xylar** [comment] 2018-01-30 17:23
This Thursday is the ALCC submission deadline so I don't want to commit to a meeting on that day.  I agree that the following Thursday is also not good.  What about another time on Monday?

**Comment by milenaveneziani** [comment] 2018-01-30 17:27
Monday besides 10am doesn't work for me (I guess 3pm would work, but then it would be too late for the East coast). How about Tue Feb 6 at 10am? the gotomeeting2 session seems to be available.

**Comment by xylar** [comment] 2018-01-30 17:30
That would work for me.

**Comment by kevans32** [comment] 2018-01-30 17:39
Tue-Thurs next week (Feb 6-8) I am at a local conference, but I could probably steal away, but just only at a couple of certain times, sorry. (all times are MST): I can do 2pm Feb 6, Wed or Thurs, anytime 8:30-11.

**Comment by milenaveneziani** [comment] 2018-01-30 17:45
2pm Feb 6?

**Comment by salilmahajan** [comment] 2018-01-30 18:03
?Sorry, I have a prior commitment on Wed. afternoon (Feb. 6). I can do Thursday.


________________________________

**Comment by milenaveneziani** [comment] 2018-01-30 18:06
Feb 6 is Tue. Would Tue at 2pm MST work for you?

**Comment by salilmahajan** [comment] 2018-01-30 18:12
?Oh. Yes, I can do that.


Thanks,

Salil.


________________________________

**Comment by milenaveneziani** [comment] 2018-01-30 19:11
ok, @xylar said that works for him too.

See meeting notes page on confluence for call details:
https://acme-climate.atlassian.net/wiki/spaces/OCNICE/pages/496435393/2018-02-06+Ocean+Ice+Special+Topics+coordination+MPAS-Analysis+A-prime

**Comment by kevans32** [comment] 2018-02-06 21:08
Is anyone on the call? I am sitting in there Gotomeeting lobby

**Comment by pwolfram** [comment] 2018-02-06 21:11
People are on the call right now...

**Comment by kevans32** [comment] 2018-02-06 21:12
WHY AM I NOT ON!

**Comment by xylar** [comment] 2018-03-03 22:23
@milenaveneziani, @kevans32 and @salilmahajan, I'm going to start working on a PR that would build a-prime as a package.  It will depend on mpas_analysis as a package as well (specifying a specific version that it is compatible with).

To minimize other development work in a-prime before the next e3sm-unified release (which should include both mpas_analysis and a-prime as python packages), I think we should just focus on those changes needed to support existing a-prime capabilities with the newest MPAS-Analysis (rather than adding new plots or the capability to compare with a reference run).  We can always follow up in the future with PRs that add a-prime support for new functionality.

**Comment by milenaveneziani** [comment] 2018-05-04 05:26
Closing this, as we are updating to MPAS-Analysis v0.7.5 in #35 (and some of the issues mentioned ere are being addressed there).

**Closed by milenaveneziani** 2018-05-04 05:26 UTC
